version: "3"
services:
  kserver:
    image: sergimc/k18:kserver
    deploy:
       replicas: 3
    networks:
      - mynet
  sshd:
    image: sergimc/k18:sshd
    networks:
      - mynet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    networks:
      - mynet
networks:
  mynet:
